### PR TITLE
Move configurations to telegraf.d, add basic configuration for CCR1009

### PR DESCRIPTION
**Pull request by Jalle19**

### CODE REVIEW

**Comment by Jalle19** [comment]
It's basically a copy of the original, minus the wifi bits.

**Comment by mprasil** [comment]
Thank you, looks good, can you fix the rename? It doesn't have proper extension.

Also the filenames can probably follow simpler naming format of `<model_name>.conf`.

**Comment by Jalle19** [comment]
@mprasil I fixed the extension, renamed the files and updated the README slightly (fixed some typos mainly)

**Review by mprasil — APPROVED** [review]
That's perfect, thank you!

**Pull request merged**
